addSbtPlugin("org.scala-js"  % "sbt-scalajs"         % "1.5.0")
addSbtPlugin("ch.epfl.scala" % "sbt-scalajs-bundler" % "0.20.0")
addSbtPlugin("com.eed3si9n"  % "sbt-buildinfo" % "0.9.0")
addSbtPlugin("org.scalameta" % "sbt-scalafmt"  % "2.4.2")
addSbtPlugin("com.github.sbt" % "sbt-pgp" % "2.1.2")