name: Publish-Demo

on:
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Node 
      uses: actions/setup-node@v2
      with:
       node-version: '12'
    - name: Set up Java 11 JDK
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: build demo
      run: sbt fullOptJS
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./demo-app/target/scala-2.13/scalajs-bundler/main/dist
        cname: www.earlyeffect.rocks