name: Scala CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Node 
      uses: actions/setup-node@v2
      with:
       node-version: '12'
    - name: Set up Java 11 JDK
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Cache
      uses: actions/cache@v2.1.3
      with:
        path: '**/node_modules'
        key: ${{ runner.os }}-build-cache-node-${{ hashFiles('**/package-lock.json') }}
    - name: Scala Caching
      uses: coursier/cache-action@v5
    - name: Run tests
      run: sbt +test
